name: Python tests + mypy, single python

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Make .env.neo4j
        uses: SpicyPizza/create-envfile@v2.0
        with:
            env_key_NEO4J_AUTH: ${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}
            env_key_NEO4J_AUTH12: neo4j/kalakala
            file_name: .env.neo4j
      - name: insane
        run: |
          cat .env.neo4j

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi


      - name: Start Neo4j
        env:
          # NEO4J_AUTH: none
          NEO4J_AUTH: ${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}
        run: docker compose up -d neo4j --wait --env NEO4J_AUTH=${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}

      - name: mypy
        env:
            NEO4J_URI: ${{ vars.NEO4J_URI }}
            NEO4J_USER: ${{ secrets.NEO4J_USER }}
            NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: |
          mypy pyzx/ tests/

      - name: Test with unittest
        env:
            NEO4J_URI: ${{ vars.NEO4J_URI }}
            NEO4J_USER: ${{ secrets.NEO4J_USER }}
            NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: |
          python -m unittest discover -s "tests" -t "." --verbose

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
