name: Python tests + mypy

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make .env.pyzx
        uses: SpicyPizza/create-envfile@v2.0
        with:
            env_key_NEO4J_URI: ${{ vars.NEO4J_URI }}
            env_key_NEO4J_USER: ${{ secrets.NEO4J_USER }}
            env_key_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
            file_name: .env.pyzx
      - name: Make .env.neo4j
        uses: SpicyPizza/create-envfile@v2.0
        with:
            env_key_NEO4J_AUTH: ${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}
            file_name: .env.neo4j


      - name: Start Neo4j
        run: docker compose up -d neo4j --wait

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi

      - name: mypy
        run: |
          mypy pyzx/ tests/

      - name: Test with unittest
        run: |
          python -m unittest discover -s "tests" -t "." --verbose

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
