name: Mypy + coverage + unittests

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ vars.SUPER_ENV }}" > .env
          echo "${{ vars.SUPER_ENV }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi

      - name: Start database
        run: docker compose up -d memgraph --wait
        continue-on-error: false


      - name: mypy
        if: always()
        run: |
          mypy pyzx/ tests/
          

      - name: Run coverage
        if: always()
        run: |
          coverage run --branch -m unittest discover tests/
          coverage xml
        continue-on-error: true

      - name: See coverage
        run: |
          coverage report -m
        continue-on-error: true


      - name: Upload to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          slug: q-sip/pyzx-
          flags: branch-dev
        continue-on-error: true

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
    

  all-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        database: ["neo4j","age","memgraph"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Create .env file
        run: |
          echo "${{ vars.SUPER_ENV }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi


      - name: Start database
        run: docker compose up -d ${{ matrix.database }} --wait
        continue-on-error: false

      - name: Test with unittest
        run: |
          python -m unittest discover -v -s tests

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
