name: Only our tests and mypy in single python

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11


      - name: Force env files
        run: |
          echo "NEO4J_AUTH=${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}" > .env.neo4j
          echo "NEO4J_URI=${{ vars.NEO4J_URI }}" > .env.pyzx
          echo "NEO4J_USER=${{ secrets.NEO4J_USER }}" >> .env.pyzx
          echo "NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}" >> .env.pyzx

      - name: Verify file size2
        run: |
          ls -l .env.neo4j
          wc -l .env.neo4j
          echo "vali moi"
          ls -l .env.pyzx
          wc -l .env.pyzx  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi


      - name: Start Neo4j
        run: docker compose up -d neo4j --wait

      - name: mypy
        if: always()
        run: |
          mypy pyzx/ tests/

      - name: Test with unittest
        if: always()
        env:
            NEO4J_URI: ${{ vars.NEO4J_URI }}
            NEO4J_USER: ${{ secrets.NEO4J_USER }}
            NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: |
          python -m unittest discover -v -s tests/test_graph_neo4j

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
