name: Dockered tests

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ls 1
        run: ls -la

      - name: Make .env.pyzx
        uses: SpicyPizza/create-envfile@v2.0
        with:
            env_key_NEO4J_URI: ${{ vars.NEO4J_URI }}
            env_key_NEO4J_USER: ${{ secrets.NEO4J_USER }}
            env_key_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
            file_name: .env.pyzx
      - name: Make .env.neo4j
        uses: SpicyPizza/create-envfile@v2.0
        with:
            env_key_NEO4J_AUTH: ${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}
            file_name: .env.neo4j

      - name: ls 2
        run: ls -la

      - name: Start Neo4j and Tests
        run: |
          # Start the neo4j and pyzx services (default)
          # And start the 'test' profile service
          docker compose --profile test up --build --exit-code-from test

      - name: ls 3
        run: ls -la

      - name: Cleanup
        # if: always()
        run: docker compose down --volumes
