name: Dockered tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force env files
        run: |
          echo "NEO4J_AUTH=${{ secrets.NEO4J_USER }}/${{ secrets.NEO4J_PASSWORD }}" > .env.neo4j
          echo "NEO4J_URI=${{ vars.NEO4J_URI }}" > .env.pyzx
          echo "NEO4J_USER=${{ secrets.NEO4J_USER }}" >> .env.pyzx
          echo "NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}" >> .env.pyzx
          echo "${{ secrets.DOCKER_ENV_PYZX}}" > .env.pyzx

      - name: Run Tests and Neo4j both from docker compose
        run: |
            docker compose --profile test up --build --exit-code-from test


      - name: Cleanup
        if: always()
        run: docker compose down --volumes
